name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: case-boost
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/cloudpanel/htdocs/camping.dev-laravel.co
          git pull
          php8.1 /usr/local/bin/composer install
          php8.1 artisan migrate --force
          php8.1 artisan route:cache
          php8.1 artisan config:cache

