name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: camping-dev
      uses: nekiro/ssh-job@main
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        command: |
          cd /home/cloudpanel/htdocs/camping.dev-laravel.co
          git pull
          php8.1 /usr/local/bin/composer install
          php8.1 artisan migrate --force
          php8.1 artisan route:cache
          php8.1 artisan config:cache

